### ISSUE TITLE
Swap/Limit nightly notification message

### ISSUE THREAD

**Issue by LivingWithHippos** [vrde/serenissimo#5]
Since a lot of smartphones show only the last message in the notification can we swap the position of the main message + notificaton with notification + main message? 

Or alternatively limit the nightly notification message to once per day

**Comment by vrde** [comment]
> Since a lot of smartphones show only the last message in the notification can we swap the position of the main message + notificaton with notification + main message?

Good point. I think I can attach the button directly to the main message and remove the one with "Le notifiche notturne ti disturbano? Se sì, schiaccia il pulsante qui sotto 👇"

![image](https://user-images.githubusercontent.com/134680/118660898-e959ad80-b7ee-11eb-9088-7d4a99d2d47e.png)

**Comment by vrde** [comment]
@LivingWithHippos I just put the patch in production. I've removed the redundant message, and I've attached the button to the main message.

If you see any weird behavior please ping me!

**Comment by LivingWithHippos** [comment]
I can confirm that the notifications are much better now
